### ISSUE TITLE
Confused finds "fuse" and "infused"

### ISSUE THREAD

**Issue by aaroncraigongithub** [publitek/stemming_dictionary#1]
The problem rule is: 

```
fuse/FSDAGCI
```

Relevant lines in the .aff file are:

```
PFX F   0     con         .
SFX S   0     s          [^sxzhy]
PFX A   0     re         .
SFX G   0     ing        [^e] 
PFX C   0     de          .
PFX I   0     in         .
```

We should group these into families that have associated meanings, ie:

fuse (v) "join or blend to form a single entity."
fuses / fusing

fuse (n) "a safety device"
fuses

fuse (n) "device in a bomb, shell, or mine to make it explode"
fuses / defuse

Other, standalone words
confuse
infuse
refuse  

I'll create a PR for this with the new rules added.

**Comment by byoungb** [comment]
Yeah I actually scripted up a script to unpack all words with prefixes.
Can you think of any reason we should not remove all of the prefixes completely.
(re, in, un, de, and dis)
My script scans for all words with any of these prefixes and then removes the prefix and then creates an entry in the dictionary with that prefix applied and any suffixes that existed in the previous entry.
So

```
fuse/FSDAGCI
```

would become

```
fuse/SG
infuse/SG
confuse/SG
refuse/SG
defuse/SG
```

Does that all sound good too you?

**Comment by byoungb** [comment]
Okay I just added the script I mentioned and added an original dictionary 5304688488bf1826b4067945783e363a7a60c534.
So I removed all the prefixes and I removed the suffix M **'s** from the dictionary, I also removed all entries that had no remaining prefixes or suffixes, since they are pointless to have when it comes to stemming.

**Comment by byoungb** [comment]
Also this weekend I added 2 more stemming rules one for a few special cases. And another for men -> man and women -> woman. But I am now realizing that some of these changes may not be for everyone, so I think that I may try and set this project up to support multiple dictionaries. What do you think?

**Comment by aaroncraigongithub** [comment]
Sorry, been out of the loop for a couple of days.

I think I agree with dropping prefixes completely.  Are there any edge cases that we'd want to keep that for?  Can't think of any, but there are a lot of words in the dictionary :)

I'm wondering if we really need multiple dictionaries.  Or better, as there isn't presently a need for it, I'm wondering if that will add complexity too early on.  For both of our needs, men -> man works well.  I'd argue that we wait until someone comes along and says they don't like that, and then we've got a reason to split into multiple dictionaries (or run a script that derives a new dictionary based on a config file) or whatever.

**Comment by aaroncraigongithub** [comment]
Also, going to close this issue, as you've resolved it.

**Comment by byoungb** [comment]
We here couldn't come up with any cases where the prefixes don't change the meaning of the word completely.
And agreed about not maintaining multiple dictionaries, I think what I will do is make my script more flexible to allow for changing what sets of conversions it runs against the original dictionary.
