### ISSUE TITLE
Consider using python hunspell package instead of popen

### ISSUE THREAD

**Issue by byoungb** [publitek/stemming_dictionary#17]

**Comment by aaroncraigongithub** [comment]
My first reaction to this is that it adds a dependency, and I'm  not sure what we gain from that, considering the stemming dictionary tool is simply meant to produce a more accurate .dic file for stemming.

Is there any other function aside from reading / writing the dic files that the python hunspell package would provide?

**Comment by byoungb** [comment]
Yeah you are probably right. I just saw it the other day and I am using Hunspell for a "Naughy Word" suppression system (so I got a list of words here https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words and then used hunspell to expand the words to create more complete blacklist regular exceptions). And I started using the python Hunspell library for that project and thought I might use it here also. But you are right what I have now works just fine. I will put a pin in this one for now.
