### ISSUE TITLE
Moth => Mother, Broth => Brother

### ISSUE THREAD

**Issue by aaroncraigongithub** [publitek/stemming_dictionary#2]
I started working on a fix for this, but I'm thinking that a framework for munging the original dictionary through some config file or something as you suggested in the previous issue is probably going to be the best solution, as it will allow us to grab updates to the upstream dictionary and run it through our script, and have the benefit of allowing people to tweak the config files as they wish.

Things to configure so far seem to be:
removing prefixes (you've done this)
removing suffixes (you've done this)
altering rule sets (we need this now for moth => mother, but also for marine => mariner without losing the 'S' rule so that we keep marine => marines, basically we need to drop ZR and keep S)

Possible other config file uses:
adding / removing words

I'm happy to do some work on this if you think this is a good direction to go in.

**Comment by aaroncraigongithub** [comment]
We actually do need to be able to add words.  Consider:

```
staple/ZRSDG
```

which should be

```
staple/SDG
```

But then you need to add 

```
stapler/S
```

**Comment by aaroncraigongithub** [comment]
Opened a PR for this:
https://github.com/publitek/stemming_dictionary/pull/3

**Comment by byoungb** [comment]
Awesome, love it.
I will add my additions to this as well.
Weird though, with my search moth and mother returned different results.
But you were write about broth and brother they returned the same results.
