### ISSUE TITLE
Beer => bees

### ISSUE THREAD

**Issue by aaroncraigongithub** [publitek/stemming_dictionary#4]

**Comment by aaroncraigongithub** [comment]
This one just came up -- putting this here so I don't forget :)

I'll add a PR sometime this week.

**Comment by byoungb** [comment]
HAHA
![beer](https://cloud.githubusercontent.com/assets/1561153/7047400/e4e41234-ddd1-11e4-95cb-dc142e28eb5d.png)
Also I see from these results I see "being" => "bee" is also a problem.
FYI I added some testing code for testing that the stemming changes work, I have even added that to travis-ci just for fun.

**Comment by byoungb** [comment]
Okay I couldn't wait on this one, so I went ahead and made changes myself.
Thanks.
